# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_ident', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('employer_url', models.CharField(blank=True, max_length=255)),
                ('employer_industry', models.CharField(blank=True, max_length=255)),
                ('patronage', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatronageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='donorData.Donor')),
            ],
            options={
                'verbose_name_plural': 'Patronage Categories',
            },
        ),
    ]
