# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='employer_url',
            field=models.URLField(max_length=255),
        ),
    ]
