# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorData', '0002_auto_20160519_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='employer_industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='employer_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
