# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donorData', '0003_auto_20160519_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patronage',
            options={'verbose_name_plural': 'Patrons'},
        ),
        migrations.AlterModelOptions(
            name='patronagecategory',
            options={'verbose_name_plural': 'Patronage Categories'},
        ),
        migrations.AddField(
            model_name='patronage',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donorData.Donor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patronagecategory',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donorData.Donor'),
            preserve_default=False,
        ),
    ]
