# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donorData', '0004_auto_20160519_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='employer_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
