# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donorData', '0005_auto_20160520_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronage',
            name='donor',
        ),
        migrations.AddField(
            model_name='donor',
            name='patronage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patronagecategory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='donorData.Donor'),
        ),
        migrations.DeleteModel(
            name='Patronage',
        ),
    ]
