# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donorData', '0006_auto_20160520_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='donor_id',
            new_name='donor_ident',
        ),
    ]
